import io, re

SENT_EN = {
  'あの 人|ひと は 私|わたし の 課長|かちょう です。': 'That person is my section chief.',
  '田中|たなか さん は 韓国人|かんこくじん です か。': 'Is Mr. Tanaka Korean?',
  '私|わたし は 大学|だいがく の 学生|がくせい です。': 'I am a university student.',
  'あれ は 大きい 企業|きぎょう です。': 'That is a large company.',
  'この 人|ひと は 会社|かいしゃ の 社長|しゃちょう です。': 'This person is the company president.',
  'あの 方|かた は 日本語|にほんご の 先生|せんせい です。': 'That person is a Japanese language teacher.',
  '私|わたし は 大学|だいがく で 勉強|べんきょう します。': 'I study at university.',
  '李|り さん は 中国人|ちゅうごくじん です。': 'Mr. Li is Chinese.',
  'あの 店員|てんいん は とても 親切|しんせつ です。': 'That store clerk is very kind.',
  '田中|たなか さん は 日本人|にほんじん です。': 'Mr. Tanaka is Japanese.',
  '私|わたし は 日本|にほん の 留学生|りゅうがくせい です。': 'I am an international student in Japan.',
  'ああ 傘|かさ は 田中|たなか さん の です か。': "Oh, is that umbrella Mr. Tanaka's?",
  'この 傘|かさ は 私|わたし の です。': 'This umbrella is mine.',
  'あれ は 何|なん です か。': 'What is that?',
  'えっ、それ は 本当|ほんとう です か。': 'What? Is that really true?',
  'この 鉛筆|えんぴつ は 誰|だれ の です か。': 'Whose pencil is this?',
  'かぎ は どこ です か。': 'Where is the key?',
  'この 写真|しゃしん は 私|わたし の 家族|かぞく です。': 'This photo is of my family.',
  'この 靴|くつ は とても きれい です。': 'These shoes are very pretty.',
  'あれ は 父|ちち の 車|くるま です。': "That is my father's car.",
  'これ は 何|なん です か。': 'What is this?',
  '毎朝|まいあさ 新聞|しんぶん を 読|よ みます。': 'I read the newspaper every morning.',
  'これ は 弟|おとうと の 自転車|じてんしゃ です。': "This is my younger brother's bicycle.",
  'あれ は 中国語|ちゅうごくご の 辞書|じしょ です。': 'That is a Chinese dictionary.',
  '机|つくえ の 上|うえ に 本|ほん が あります。': 'There is a book on the desk.',
  'これ は 私|わたし の 手帳|てちょう です。': 'This is my planner.',
  '日本語|にほんご の 辞書|じしょ を 買|か いました。': 'I bought a Japanese dictionary.',
  '私|わたし は 毎日|まいにち 日本語|にほんご を 勉強|べんきょう します。': 'I study Japanese every day.',
  'これ は 母|はは の 傘|かさ です。': "This is my mother's umbrella.",
  'これ は 北京|ぺきん の 名産品|めいさんひん です。': 'This is a specialty product from Beijing.',
  'これ は 日本語|にほんご の 本|ほん です。': 'This is a Japanese language book.',
  'あれ は 新しい パソコン です か。': 'Is that a new computer?',
  '受付|うけつけ は 一階|いっかい に あります。': 'The reception desk is on the first floor.',
  '駅|えき の 近く|ちかく に 喫茶店|きっさてん が あります。': 'There is a coffee shop near the station.',
  'あなた の 国|くに は どこ です か。': 'What country are you from?',
  '駅|えき の 周辺|しゅうへん に 店|みせ が たくさん あります。': 'There are many shops around the station.',
  '食堂|しょくどう は 三階|さんかい に あります。': 'The cafeteria is on the third floor.',
  '事務所|じむしょ は どこ に あります か。': 'Where is the office?',
  'あの 建物|たてもの は 何|なん です か。': 'What is that building?',
  '銀行|ぎんこう の 隣|となり に 郵便局|ゆうびんきょく が あります。': 'There is a post office next to the bank.',
  '病院|びょういん は 駅|えき の そば に あります。': 'The hospital is near the station.',
  'この 服|ふく は どこ の です か。': 'Where are these clothes from?',
  '木曜日|もくようび に 授業|じゅぎょう が あります。': 'There is a class on Thursday.',
  '郵便局|ゆうびんきょく は 駅|えき の 近く|ちかく に あります。': 'The post office is near the station.',
  '本屋|ほんや は デパート の 中|なか に あります。': 'The bookstore is inside the department store.',
  'エスカレーター は あそこ に あります。': 'The escalator is over there.',
  'コンビニ は 学校|がっこう の 隣|となり に あります。': 'The convenience store is next to the school.',
  'これ は 新しい デジカメ です。': 'This is a new digital camera.',
  'デパート は 駅|えき の 前|まえ に あります。': 'The department store is in front of the station.',
  'トイレ は どこ に あります か。': 'Where is the restroom?',
  '机|つくえ の 上|うえ に 眼鏡|めがね が あります。': 'There are glasses on the desk.',
  '教室|きょうしつ に 生徒|せいと が います。': 'There are students in the classroom.',
  '居間|いま に 家族|かぞく が います。': 'The family is in the living room.',
  '公園|こうえん に 子供|こども が います。': 'There are children in the park.',
  '私|わたし に は 妹|いもうと が います。': 'I have a younger sister.',
  '両親|りょうしん は 今|いま 家|いえ に います。': 'My parents are home right now.',
  'あなた に は 兄弟|きょうだい が います か。': 'Do you have any siblings?',
  'あそこ に 男|おとこ の 人|ひと が います。': 'There is a man over there.',
  '駅|えき の 前|まえ に 花屋|はなや が あります。': 'There is a flower shop in front of the station.',
  '教室|きょうしつ に 学生|がくせい が たくさん います。': 'There are many students in the classroom.',
  '庭|にわ に 猫|ねこ が います。': 'There is a cat in the garden.',
  '公園|こうえん に 子供|こども が 三人|さんにん います。': 'There are three children in the park.',
  '外|そと に 犬|いぬ が います。': 'There is a dog outside.',
  '地下鉄|ちかてつ の 駅|えき は あそこ に あります。': 'The subway station is over there.',
  '箱|はこ の 中|なか に 何|なに が あります か。': 'What is inside the box?',
  '庭|にわ に 木|き が あります。': 'There is a tree in the garden.',
  '箱|はこ の 中|なか に 猫|ねこ が います。': 'There is a cat inside the box.',
  '花屋|はなや は 駅|えき の 前|まえ に あります。': 'The flower shop is in front of the station.',
  '売店|ばいてん は 一階|いっかい に あります。': 'The kiosk is on the first floor.',
  '本棚|ほんだな に 本|ほん が たくさん あります。': 'There are many books on the bookshelf.',
  'ビデオ は 居間|いま に あります。': 'The video player is in the living room.',
  '明日|あした は 休み|やすみ です。': 'Tomorrow is a day off.',
  '毎朝|まいあさ 六時|ろくじ に 起き|おき ます。': 'I wake up at six every morning.',
  '今|いま 何時|なんじ です か。': 'What time is it now?',
  'おととい 友達|ともだち に 会い|あい ました。': 'I met a friend the day before yesterday.',
  '火曜日|かようび に 試験|しけん が あります。': 'There is an exam on Tuesday.',
  '学校|がっこう は 九時|くじ に 始まり|はじまり ます。': "School starts at nine o'clock.",
  '昨日|きのう 映画|えいが を 見|み ました。': 'I watched a movie yesterday.',
  '今朝|けさ パン を 食べ|たべ ました。': 'I ate bread this morning.',
  '来月|らいげつ 研修|けんしゅう が あります。': 'There is a training session next month.',
  '月曜日|げつようび から 仕事|しごと が 始まり|はじまり ます。': 'Work starts from Monday.',
  '今週|こんしゅう は 忙し|いそがし いです。': 'I am busy this week.',
  '試験|しけん は 難し|むずかし かった です。': 'The exam was difficult.',
  '仕事|しごと は 八時|はちじ に 終わり|おわり ます。': 'Work ends at eight.',
  '来週|らいしゅう 大阪|おおさか に 出張|しゅっちょう します。': 'I am going on a business trip to Osaka next week.',
  '先週|せんしゅう 旅行|りょこう に 行き|いき ました。': 'I went on a trip last week.',
  '今日|きょう 遅刻|ちこく して しまい ました。': 'I ended up being late today.',
  'いつも 早く|はやく 起き|おき ます。': 'I always wake up early.',
  '毎週|まいしゅう 土曜日|どようび に テニス を します。': 'I play tennis every Saturday.',
  '毎日|まいにち 新聞|しんぶん を 読み|よみ ます。': 'I read the newspaper every day.',
  '毎晩|まいばん お風呂|おふろ に 入り|はいり ます。': 'I take a bath every evening.',
  '来週|らいしゅう 友達|ともだち と 会い|あい ます。': 'I am meeting a friend next week.',
  '来月|らいげつ 日本|にほん へ 旅行|りょこう します。': 'I am traveling to Japan next month.',
  '土曜日|どようび に パーティー が あります。': 'There is a party on Saturday.',
  '来月|らいげつ 引っ越し|ひっこし を します。': 'I am moving next month.',
  'いっしょに 昼ご飯|ひるごはん を 食べ|たべ ませんか。': 'Would you like to have lunch together?',
  '弟|おとうと は 学生|がくせい です。': 'My younger brother is a student.',
  'この 交通機関|こうつうきかん は 便利|べんり です。': 'This public transportation is convenient.',
  '先月|せんげつ 新しい|あたらしい 仕事|しごと を 始め|はじめ ました。': 'I started a new job last month.',
  'たしか 三時|さんじ に 来る|くる と 言い|いい ました。': 'I believe they said they would come at three.',
  '友達|ともだち と 公園|こうえん で 遊び|あそび ました。': 'I hung out with my friends at the park.',
  '飛行機|ひこうき で 東京|とうきょう へ 行き|いき ます。': 'I am going to Tokyo by plane.',
  'バス で 学校|がっこう に 行き|いき ます。': 'I go to school by bus.',
  '昼ご飯|ひるごはん に 親子丼|おやこどん を 食べ|たべ ました。': 'I had oyakodon for lunch.',
  'これから 出発|しゅっぱつ します。': 'We are departing now.',
  '毎週|まいしゅう 部屋|へや を 掃除|そうじ します。': 'I clean my room every week.',
  '卵|たまご を 三つ|みっつ 買い|かい ました。': 'I bought three eggs.',
  'では また 明日|あした。': 'See you tomorrow.',
  '日曜日|にちようび に 動物園|どうぶつえん へ 行き|いき ます。': 'I am going to the zoo on Sunday.',
  'この 申込書|もうしこみしょ に 名前|なまえ を 書い|かい て ください。': 'Please write your name on this application form.',
  '音楽|おんがく を 聴き|きき ながら 勉強|べんきょう します。': 'I study while listening to music.',
  '毎週|まいしゅう 友達|ともだち と サッカー を します。': 'I play soccer with my friends every week.',
  '公園|こうえん で テニス を し ました。': 'I played tennis at the park.',
  '今朝|けさ パン と コーヒー を 食べ|たべ ました。': 'I had bread and coffee this morning.',
  '動物園|どうぶつえん で パンダ を 見|み ました。': 'I saw a panda at the zoo.',
  '友達|ともだち に 花|はな を あげます。': 'I will give flowers to my friend.',
  '子供|こども と 紙飛行機|かみひこうき を 作り|つくり ました。': 'I made paper airplanes with my child.',
  '韓国語|かんこくご を 少し|すこし 話せ|はなせ ます。': 'I can speak a little Korean.',
  '旅行|りょこう の 記念品|きねんひん を 買い|かい ました。': 'I bought a souvenir from my trip.',
  'その 件|けん について 話し|はなし ましょう。': "Let's talk about that matter.",
  'この 荷物|にもつ を 航空便|こうくうびん で 送り|おくり ます。': 'I will send this luggage by airmail.',
  '新聞紙|しんぶんし で 包み|つつみ ます。': 'I will wrap it in newspaper.',
  '住所|じゅうしょ を 教え|おしえ て ください。': 'Please tell me your address.',
  '母|はは に 花|はな を あげます。': 'I will give flowers to my mother.',
  '夕方|ゆうがた 六時|ろくじ に 帰り|かえり ます。': 'I will be home by six in the evening.',
  '旅行|りょこう の 写真集|しゃしんしゅう を 作り|つくり ました。': 'I made a photo album from my trip.',
  '友達|ともだち に チョコレート を あげます。': 'I will give chocolate to my friend.',
  'この パンフレット を 読ん|よん で ください。': 'Please read this pamphlet.',
  'ボールペン で 名前|なまえ を 書い|かい て ください。': 'Please write your name with a ballpoint pen.',
  '母|はは の 料理|りょうり は おいしい です。': "My mother's cooking is delicious.",
  'この ケーキ は とても おいしい です。': 'This cake is very delicious.',
  '日本|にほん に は 温泉|おんせん が たくさん あります。': 'There are many hot springs in Japan.',
  '紙|かみ に 名前|なまえ を 書|か いて ください。': 'Please write your name on the paper.',
  '歌舞伎|かぶき を 見|み た こと が あります か。': 'Have you ever seen kabuki?',
  'この 猫|ねこ は とても かわいい です。': 'This cat is very cute.',
  '薬|くすり を 飲|の んで ください。': 'Please take your medicine.',
  '四川料理|しせんりょうり は 辛|から い です。': 'Sichuan cuisine is spicy.',
  'あの 女性|じょせい は きれい です。': 'That woman is beautiful.',
  'ちょうど 三時|さんじ に 来|き て ください。': "Please come at exactly three o'clock.",
  '今日|きょう は 天気|てんき が いい です。': 'The weather is nice today.',
  'この 料理|りょうり は まずい です。': 'This dish tastes bad.',
  '水|みず を 一杯|いっぱい ください。': 'Please give me a glass of water.',
  '山|やま に 登|のぼ った こと が あります か。': 'Have you ever climbed a mountain?',
  '夏祭|なつまつ り に 浴衣|ゆかた を 着|き ます。': 'I will wear a yukata to the summer festival.',
  'スープ は あたたかい です。': 'The soup is warm.',
  '北京ダック|ペキンダック は 有名|ゆうめい な 料理|りょうり です。': 'Peking duck is a famous dish.',
  '夏|なつ に 海|うみ へ 行|い きたい です。': 'I want to go to the beach in summer.',
  '明|あか るい 人|ひと が 好|す きです。': 'I like cheerful people.',
  '今日|きょう は 雨|あめ が 降|ふ って います。': 'It is raining today.',
  'いろいろ な 国|くに を 旅行|りょこう したい です。': 'I want to travel to various countries.',
  'この 問題|もんだい は 簡単|かんたん です。': 'This problem is easy.',
  '毎日|まいにち 元気|げんき に 学校|がっこう へ 行|い きます。': 'I go to school cheerfully every day.',
  '故郷|こきょう に 帰|かえ りたい です。': 'I want to go back to my hometown.',
  '魚|さかな を 食|た べる こと が 好|す き です。': 'I like eating fish.',
  'この 作品|さくひん は すばらしい です。': 'This work is wonderful.',
  '試合|しあい に 負|ま けて 残念|ざんねん です。': 'It is a shame that we lost the match.',
  '来週|らいしゅう 修学旅行|しゅうがくりょこう が あります。': 'There is a school trip next week.',
  '駅員|えきいん さん は 親切|しんせつ に 教|おし えて くれました。': 'The station attendant kindly helped me.',
  '自動車|じどうしゃ で 会社|かいしゃ に 行|い きます。': 'I go to work by car.',
  '日本|にほん で の 生活|せいかつ は 楽|たの しい です。': 'Life in Japan is enjoyable.',
  '世界|せかい を 旅行|りょこう したい です。': 'I want to travel around the world.',
  'この 彫刻|ちょうこく は 有名|ゆうめい な 芸術家|げいじゅつか の 作品|さくひん です。': 'This sculpture is the work of a famous artist.',
  'いい 所|ところ を 知|し って います か。': 'Do you know any good places?',
  '渋谷|しぶや は にぎやか な 町|まち です。': 'Shibuya is a lively town.',
  'かわいい 人形|にんぎょう を もらいました。': 'I received a cute doll.',
  '今日|きょう は 暇|ひま です か。': 'Are you free today?',
  '部長|ぶちょう は 今 会議|かいぎ 中|ちゅう です。': 'The department manager is in a meeting right now.',
  '平日|へいじつ は バス で 通勤|つうきん します。': 'I commute by bus on weekdays.',
  'この 物|もの は 誰|だれ の です か。': 'Whose is this?',
  '秋|あき に 紅葉|もみじ を 見|み に 行|い きます。': 'I will go to see the autumn leaves.',
  'この 店|みせ は 有名|ゆうめい です。': 'This shop is famous.',
  'この 町|まち は 交通|こうつう が 不便|ふべん です。': 'This town has inconvenient transportation.',
  'どんな 音楽|おんがく が 好|す き です か。': 'What kind of music do you like?',
  'スマホ は とても 便利|べんり です。': 'Smartphones are very convenient.',
  '脚|あし が 痛|いた い です。': 'My leg hurts.',
  '父|ちち は 車|くるま の 運転|うんてん が 上手|じょうず です。': 'My father is a good driver.',
  'うーん、ちょっと 難|むずか しい です ね。': "Hmm, that's a bit difficult, isn't it.",
  '英語|えいご を 勉強|べんきょう して います。': 'I am studying English.',
  '午後|ごご に 会議|かいぎ が あります。': 'There is a meeting in the afternoon.',
  '外国|がいこく に 住|す みたい です。': 'I want to live in a foreign country.',
  '果物|くだもの の 中|なか で りんご が 一番|いちばん 好|す き です。': 'Among fruits, I like apples the most.',
  '水泳|すいえい を 習|なら って います。': 'I am taking swimming lessons.',
  '日本語|にほんご が できます か。': 'Can you speak Japanese?',
  '雨|あめ です。ですから、傘|かさ を 持|も って ください。': 'It is raining. So please bring an umbrella.',
  '時々|ときどき 映画|えいが を 見|み に 行|い きます。': 'I sometimes go to see movies.',
  'どうして 学校|がっこう を 休|やす みました か。': 'Why were you absent from school?',
  '肉|にく より 魚|さかな の ほう が 好|す き です。': 'I prefer fish over meat.',
  '私|わたし は 料理|りょうり が 下手|へた です。': 'I am not good at cooking.',
  'また 来|き て ください。': 'Please come again.',
  '窓|まど を 開|あ けて も いい です か。': 'Is it okay if I open the window?',
  'この 着物|きもの は きれい な 模様|もよう が あります。': 'This kimono has a beautiful pattern.',
  '友達|ともだち と カラオケ に 行|い きます。': 'I am going to karaoke with my friends.',
  '赤|あか い バラ を プレゼント しました。': 'I gave red roses as a gift.',
  '夏|なつ に ヒマワリ が 咲|さ きます。': 'Sunflowers bloom in summer.',
  'ポップス を 聞|き く こと が 好|す き です。': 'I like listening to pop music.',
  '兄|あに は 医者|いしゃ です。': 'My older brother is a doctor.',
  'この 道|みち は 夜|よる でも 安全|あんぜん です。': 'This road is safe even at night.',
  'クラス で いちばん 背|せ が 高|たか い です。': 'I am the tallest in the class.',
  '一番|いちばん 好|す き な 季節|きせつ は 春|はる です。': 'My favorite season is spring.',
  '寿司|すし を 食|た べに 行|い きましょう。': "Let's go eat sushi.",
  '席|せき は まだ あります か。': 'Are there still seats available?',
  '日本酒|にほんしゅ を 飲|の んだ こと が あります か。': 'Have you ever drunk sake?',
  '日本料理|にほんりょうり の 中|なか で 寿司|すし が 一番|いちばん 好|す き です。': 'Among Japanese dishes, I like sushi the most.',
  '冬|ふゆ は とても 寒|さむ い です。': 'Winter is very cold.',
  '春|はる に なると 桜|さくら が 咲|さ きます。': 'When spring comes, the cherry blossoms bloom.',
  'やっぱり 日本|にほん が 一番|いちばん いい です。': 'Japan really is the best after all.',
  'この 店|みせ に は いろいろ な 種類|しゅるい の ケーキ が あります。': 'This shop has many different kinds of cakes.',
  'バナナ は 甘|あま くて おいしい です。': 'Bananas are sweet and delicious.',
  '冬|ふゆ に ミカン を よく 食|た べます。': 'I often eat mandarin oranges in winter.',
  '私|わたし の クラス に は 二十人|にじゅうにん います。': 'There are twenty people in my class.',
  '友達|ともだち と 居酒屋|いざかや で 飲|の みました。': 'I went drinking with friends at an izakaya.',
  '車|くるま を 修理|しゅうり に 出|だ しました。': 'I took my car in for repairs.',
  '駅|えき まで 20 分|ふん かかります。': 'It takes 20 minutes to the station.',
  '髪|かみ を 切|き りたいです。': 'I want to get a haircut.',
  'だいたい 1 時間|じかん かかります。': 'It takes about an hour.',
  '生|なま ビール を 一杯|いっぱい ください。': 'One draft beer, please.',
  '荷物|にもつ が 多|おお すぎます。': 'There is too much luggage.',
  'ほか に 何|なに か ありますか。': 'Is there anything else?',
  '旅行|りょこう の アルバム を 見|み せてください。': 'Please show me your travel photo album.',
  '週末|しゅうまつ に ボーリング を しませんか。': 'Would you like to go bowling this weekend?',
  'ああ、そうですか。': 'Oh, is that so?',
  '切手|きって を 集|あつ めるのが 趣味|しゅみ です。': 'My hobby is collecting stamps.',
  '荷物|にもつ を 海外|かいがい に 送|おく りました。': 'I sent a package overseas.',
  '新聞|しんぶん の 記事|きじ を 読|よ みました。': 'I read a newspaper article.',
  'こう やってみてください。': 'Please try doing it this way.',
  '次|つぎ の 交差点|こうさてん を 右|みぎ に 曲|ま がってください。': 'Turn right at the next intersection.',
  '一緒|いっしょ に 食事|しょくじ しませんか。': 'Would you like to have a meal together?',
  '書類|しょるい に サイン を してください。': 'Please sign the documents.',
  '部屋|へや を 整理|せいり しました。': 'I tidied up the room.',
  '毎朝|まいあさ 公園|こうえん で 太極拳|たいきょくけん を しています。': 'I practice tai chi in the park every morning.',
  '角|かど を 曲|ま がると 銀行|ぎんこう があります。': 'There is a bank around the corner.',
  'この 問題|もんだい は なかなか 難|むずか しいです。': 'This problem is quite difficult.',
  '川|かわ に 橋|はし を 渡|わた りました。': 'I crossed the bridge over the river.',
  '船便|ふなびん で 送|おく ると 安|やす いです。': 'It is cheaper to send it by sea mail.',
  '右|みぎ に 曲|ま がってください。': 'Please turn right.',
  'この 道|みち を まっすぐ 行|い ってください。': 'Please go straight down this road.',
  '電気|でんき を 消|け してください。': 'Please turn off the lights.',
  '公園|こうえん で バーベキュー を しました。': 'We had a barbecue in the park.',
  'そんな 無理|むり な お願|ねが いはできません。': 'I cannot grant such an unreasonable request.',
  '電車|でんしゃ に 遅|おく れそうなので 急|いそ いでください。': 'Please hurry, we might be late for the train.',
  '財布|さいふ を 落|お としてしまいました。': 'I dropped my wallet.',
  '風邪|かぜ を ひいてしまいました。': 'I caught a cold.',
  '気|き を つけてください。': 'Please be careful.',
  'この レストラン は 禁煙|きんえん です。': 'This restaurant is non-smoking.',
  '携帯電話|けいたいでんわ を 忘|わす れてしまいました。': 'I forgot my mobile phone.',
  'この 美術館|びじゅつかん は 撮影禁止|さつえいきんし です。': 'Photography is not allowed in this museum.',
  '市役所|しやくしょ で 手続|てつづ きをしました。': 'I completed the paperwork at city hall.',
  '毎日|まいにち 8 時間|じかん の 睡眠|すいみん が 必要|ひつよう です。': 'Eight hours of sleep per day is necessary.',
  'あそこ は 立入禁止|たちいりきんし です。': 'No entry is allowed over there.',
  'ここ は 駐車禁止|ちゅうしゃきんし です。': 'Parking is not allowed here.',
  '火|ひ に 気|き を つけてください。': 'Please be careful with fire.',
  'もしもし、田中|たなか さんですか。': 'Hello, is this Mr. Tanaka?',
  '近|ちか くに 薬局|やっきょく が ありますか。': 'Is there a pharmacy nearby?',
  '公園|こうえん の ベンチ に 座|すわ りました。': 'I sat on a bench in the park.',
  '湖|みずうみ で ボート に 乗|の りました。': 'I went boating on the lake.',
  '足|あし が 痛|いた いです。': 'My foot hurts.',
  '空港|くうこう の 警備|けいび は 厳|きび しいです。': 'Security at the airport is strict.',
  '財布|さいふ を なくしてしまいました。': 'I lost my wallet.',
  '明日|あした 7 時|じ に 起|お こしてください。': "Please wake me up at 7 o'clock tomorrow.",
  'お店|みせ の 看板|かんばん が 大|おお きいです。': "The shop's sign is large.",
  'この 機械|きかい の 使|つか い方|かた を 教|おし えてください。': 'Please show me how to use this machine.',
  '有名|ゆうめい な 建築家|けんちくか が 設計|せっけい しました。': 'A famous architect designed it.',
  '子|こ どもたち が 公園|こうえん で 遊|あそ んでいます。': 'Children are playing in the park.',
  'どの 航空会社|こうくうかいしゃ で 予約|よやく しましたか。': 'Which airline did you book with?',
  'テレビ の 広告|こうこく を 見|み ました。': 'I saw a television commercial.',
  '水筒|すいとう に 水|みず を 入|い れました。': 'I filled my water bottle with water.',
  'この 建物|たてもの の 設計|せっけい はすばらしいです。': 'The design of this building is wonderful.',
  'この 機械|きかい の 操作|そうさ は 簡単|かんたん です。': 'This machine is easy to operate.',
  '展示場|てんじじょう で 新|あたら しい 製品|せいひん を 見|み ました。': 'I saw new products at the exhibition hall.',
  'この 部屋|へや の 天井|てんじょう は 高|たか いです。': 'The ceiling in this room is high.',
  '公園|こうえん の 緑|みどり が きれいです。': 'The greenery in the park is beautiful.',
  '入場料|にゅうじょうりょう は いくらですか。': 'How much is the admission fee?',
  '鼻|はな が 痛|いた いです。': 'My nose hurts.',
  '目|め が 疲|つか れました。': 'My eyes are tired.',
  '何|なに か 問題|もんだい が ありますか。': 'Is there any problem?',
  '指|ゆび を 切|き ってしまいました。': 'I accidentally cut my finger.',
  '駅|えき の 横|よこ に 本屋|ほんや があります。': 'There is a bookstore next to the station.',
  '毎日|まいにち ピアノ を 練習|れんしゅう しています。': 'I practice piano every day.',
  'クリスマスツリー を かざりました。': 'I decorated the Christmas tree.',
  '話|はな し合|あ いの 相手|あいて を 決|き めましょう。': "Let's decide who will be the discussion partner.",
  '健康|けんこう の ために 毎日|まいにち 運動|うんどう しています。': 'I exercise every day for my health.',
  '恋人|こいびと と 映画|えいが を 見|み に 行|い きました。': 'I went to see a movie with my partner.',
  '今年|ことし の 夏|なつ は 暑|あつ かったです。': 'This summer was hot.',
  '朝|あさ の 電車|でんしゃ はいつも 混|こ んでいます。': 'The morning train is always crowded.',
  '今度|こんど 一緒|いっしょ に 食事|しょくじ しましょう。': "Let's have a meal together sometime.",
  'まず 自己|じこ 紹介|しょうかい を してください。': 'First, please introduce yourself.',
  '新|あたら しい 洋服|ようふく を 買|か いました。': 'I bought new clothes.',
  '立派|りっぱ な 建物|たてもの ですね。': 'What an impressive building.',
  '恋愛|れんあい は 人生|じんせい を 豊|ゆた かにします。': 'Romance enriches life.',
  '新|あたら しい ノートパソコン を 買|か いたいです。': 'I want to buy a new laptop.',
  'この 空|そら は 青|あお いですね。': "The sky is blue, isn't it.",
  '赤|あか い バラを 買|か いました。': 'I bought red roses.',
  '日曜日|にちようび 以外|いがい は 毎日|まいにち 働|はたら きます。': 'I work every day except Sundays.',
  'どんな 色|いろ が 好|す きですか。': 'What colors do you like?',
  '将来|しょうらい は 医者|いしゃ になりたいです。': 'I want to become a doctor in the future.',
  '隣|となり の 部屋|へや が うるさいです。': 'The room next door is noisy.',
  'もう 少|すこ し 大|おお きい 声|こえ で 話|はな してください。': 'Please speak a little louder.',
  '計画|けいかく を 変|か えることにしました。': 'I decided to change the plan.',
  '山|やま の 空気|くうき は きれいです。': 'The air in the mountains is clean.',
  '来年|らいねん から 社会人|しゃかいじん になります。': 'I will be entering the workforce starting next year.',
  '新春|しんしゅん セールで コートを 買|か いました。': 'I bought a coat at the New Year sale.',
  '時間|じかん がありません。': "I don't have time.",
  '旅行|りょこう の 準備|じゅんび はもうできましたか。': 'Have you finished preparing for the trip?',
  '外|そと から 大|おお きな 音|おと がしました。': 'There was a loud noise from outside.',
  'この 店|みせ は 値段|ねだん が 安|やす いです。': 'The prices at this store are cheap.',
  'セールで 半額|はんがく になっています。': 'It is half price at the sale.',
  '昨日|きのう から 病気|びょうき で 会社|かいしゃ を 休|やす んでいます。': 'I have been out sick from work since yesterday.',
  '息子|むすこ は 今年|ことし 大学|だいがく に 入|はい りました。': 'My son entered university this year.',
  'もっと ゆっくり 話|はな してください。': 'Please speak more slowly.',
  '旅行|りょこう ガイドを 買|か って 準備|じゅんび しました。': 'I bought a travel guide and prepared for the trip.',
  '彼女|かのじょ は ファッション デザイナーです。': 'She is a fashion designer.',
  '子供|こども のころ パイロットになりたかったです。': 'When I was a child, I wanted to become a pilot.',
  '毎週|まいしゅう 英会話|えいかいわ の クラスに 通|かよ っています。': 'I attend an English conversation class every week.',
  '遠慮|えんりょ しないで、もっと 食|た べてください。': "Don't hold back — please eat more.",
  'あの レストランは 高級|こうきゅう で 値段|ねだん が 高|たか いです。': 'That restaurant is upscale and the prices are high.',
  '今日|きょう は 残業|ざんぎょう しなければなりません。': 'I have to work overtime today.',
  'この 店|みせ の 品物|しなもの は 質|しつ がいいです。': 'The goods at this store are of good quality.',
  '子供|こども が 遅|おそ いので 心配|しんぱい しています。': 'My child is late, so I am worried.',
  '来月|らいげつ から 上級|じょうきゅう クラスに 進|すす みます。': 'I will be moving up to the advanced class starting next month.',
  '日本語|にほんご が だいぶ 上手|じょうず になりました。': 'My Japanese has gotten quite good.',
  'それは 本当|ほんとう のことですか。': 'Is that really true?',
  'やっと 仕事|しごと が 終|お わりました。': 'I finally finished work.',
  'パスポートを 忘|わす れないでください。': "Please don't forget your passport.",
  'レポートを 来週|らいしゅう までに 出|だ してください。': 'Please submit the report by next week.',
  '大学|だいがく の 寮|りょう に 住|す んでいます。': 'I live in a university dormitory.',
  '日本|にほん の 文化|ぶんか に 興味|きょうみ があります。': 'I am interested in Japanese culture.',
  'おなかが 痛|いた いので 病院|びょういん に 行|い きます。': 'My stomach hurts, so I am going to the hospital.',
  '予約|よやく の 時間|じかん を 確認|かくにん してください。': 'Please confirm the reservation time.',
  'りんごの 皮|かわ を むいてください。': 'Please peel the apple.',
  '私|わたし の 特技|とくぎ は 料理|りょうり です。': 'My special skill is cooking.',
  '胡弓|こきゅう を 弾|ひ くことができます。': 'I can play the erhu.',
  '今日|きょう は 私|わたし が ごちそうします。': "Today, it's my treat.",
  'お 正月|しょうがつ に 獅子舞|ししまい を 見|み ました。': "I watched a lion dance at New Year's.",
  '春節|しゅんせつ に 家族|かぞく で 集|あつ まります。': 'My family gathers together for the Lunar New Year.',
  '子供|こども のころから 書道|しょどう を 習|なら っています。': 'I have been learning calligraphy since I was a child.',
  '自分|じぶん で 料理|りょうり を 作|つく ります。': 'I cook for myself.',
  '洗濯機|せんたくき が 壊|こわ れてしまいました。': 'The washing machine broke.',
  'みんなで 一緒|いっしょ に 食|た べましょう。': "Let's all eat together.",
  '毎日|まいにち ギターを 練習|れんしゅう しています。': 'I practice guitar every day.',
  '毎朝|まいあさ 30 分|ふん 運動|うんどう しています。': 'I exercise for 30 minutes every morning.',
  'この 歌|うた を 聞|き くと 子供|こども のころを 思|おも い 出|だ します。': 'When I hear this song, it reminds me of my childhood.',
  'いつも 助|たす けてくれて 感謝|かんしゃ しています。': 'I am grateful that you always help me.',
  '休憩時間|きゅうけいじかん に コーヒーを 飲|の みます。': 'I drink coffee during my break.',
  '北京|ぺきん で 京劇|きょうげき を 見|み ました。': 'I watched Peking opera in Beijing.',
  '海外|かいがい で 働|はたら いた 経験|けいけん があります。': 'I have experience working abroad.',
  '彼|かれ の 言葉|ことば に 感動|かんどう しました。': 'I was moved by his words.',
  '駐車場|ちゅうしゃじょう は どこですか。': 'Where is the parking lot?',
  '結果|けっか を 上司|じょうし に 報告|ほうこく します。': 'I will report the results to my supervisor.',
  'レストランを 予約|よやく しておきました。': 'I made a reservation at the restaurant in advance.',
  '連休|れんきゅう に 旅行|りょこう に 行|い く 予定|よてい です。': 'I plan to go on a trip during the consecutive holidays.',
  'ゴールデンウィークに 何|なに をしますか。': 'What are you going to do during Golden Week?',
  'あんまり 辛|から いので 食|た べられません。': "It's too spicy, so I can't eat it.",
  'いや、そんなことはありません。': "No, that's not the case at all.",
  'プレゼントをもらって とても うれしいです。': "I'm very happy to have received a present.",
  '子供|こども に おもちゃを 買|か ってあげました。': 'I bought a toy for my child.',
  '彼女|かのじょ は 有名|ゆうめい な 歌手|かしゅ です。': 'She is a famous singer.',
  '近|ちか くで 火事|かじ がありました。': 'There was a fire nearby.',
  '急|きゅう な 用事|ようじ ができてしまいました。': 'Something urgent has come up.',
  'セールの 期間|きかん はいつまでですか。': 'How long does the sale last?',
  '携帯|けいたい を 忘|わす れて 家|いえ に 帰|かえ りました。': 'I left my phone behind and went home.',
  '来週|らいしゅう 田中|たなか さんの 送別会|そうべつかい があります。': "There is a farewell party for Mr. Tanaka next week.",
  '都合|つごう がいい 日|ひ を 教|おし えてください。': 'Please let me know a day that works for you.',
  '来月|らいげつ 大阪|おおさか に 転勤|てんきん することになりました。': 'It has been decided that I will be transferred to Osaka next month.',
  '明日|あした の 予定|よてい は 何|なに ですか。': 'What are your plans for tomorrow?',
  '何|なに かあったらすぐ 連絡|れんらく してください。': 'Please contact me right away if anything comes up.',
  'この 料理|りょうり は 味|あじ がいいですね。': "This dish tastes great, doesn't it?",
  '道|みち を 渡|わた るとき 気|き をつけてください。': 'Please be careful when crossing the street.',
  'このスカートの 生地|きじ はとても 柔|やわ らかいです。': 'The fabric of this skirt is very soft.',
  '週末|しゅうまつ は 友達|ともだち と 映画|えいが を 見|み に 行|い きます。': "I'm going to see a movie with friends this weekend.",
  '船|ふね で 島|しま に 行|い きました。': 'I went to the island by boat.',
  '閉店時刻|へいてんじこく は 何時|なんじ ですか。': 'What time do you close?',
  'バスの 中|なか は 人|ひと が いっぱいです。': 'The bus is packed with people.',
  '午後|ごご から 外出|がいしゅつ する 予定|よてい です。': 'I plan to go out in the afternoon.',
  '大学|だいがく で 日本|にほん の 歴史|れきし を 研究|けんきゅう しています。': 'I am researching Japanese history at university.',
  'あの 選手|せんしゅ は すごい 力|ちから を 持|も っています。': 'That athlete has incredible strength.',
  'あの 店員|てんいん はとても 丁寧|ていねい に 説明|せつめい してくれました。': 'That store clerk explained everything very politely.',
  '今朝|けさ 寝坊|ねぼう して 電車|でんしゃ に 乗|の り 遅|おく れました。': 'I overslept this morning and missed the train.',
  '法律|ほうりつ を 守|まも らなければなりません。': 'We must obey the law.',
}

with io.open(r'C:\Users\Mo_Tsai\Desktop\Google Drive\自動化測試資料夾\Japanese-tutor\cards_data.js', 'r', encoding='utf-8') as f:
    content = f.read()

def add_sent_en(m):
    full = m.group(0)
    sent_match = re.search(r"sentence: '([^']*)'", full)
    if not sent_match:
        return full
    sent = sent_match.group(1)
    en = SENT_EN.get(sent, '')
    en_escaped = en.replace("'", "\\'")
    return re.sub(
        r"(sentenceMeaning: '[^']*')",
        r"\1, sentenceMeaningEn: '" + en_escaped + "'",
        full
    )

new_content = re.sub(r'\{[^}]+\}', add_sent_en, content)

with io.open(r'C:\Users\Mo_Tsai\Desktop\Google Drive\自動化測試資料夾\Japanese-tutor\cards_data.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

missing = len(re.findall(r"sentenceMeaningEn: ''", new_content))
total = new_content.count('sentenceMeaningEn')
print(f'Done. {total} cards updated, {missing} missing translations.')
