import io, re

EN = {
  '課長':'section chief','韓国人':'Korean (person)','学生':'university student',
  '企業':'company, enterprise','社長':'company president','先生':'teacher',
  '大学':'university','中国人':'Chinese (person)','店員':'shop clerk',
  '日本人':'Japanese (person)','留学生':'exchange student','ああ':'that one; I see',
  '傘':'umbrella','あれ':'that (over there)','えっ':'huh? what?',
  '鉛筆':'pencil','かぎ':'key, lock','家族':'family','靴':'shoes',
  '車':'car','これ':'this','新聞':'newspaper','自転車':'bicycle',
  '中国語':'Chinese language','机':'desk','手帳':'notebook, planner',
  '辞書':'dictionary','何':'what','日本語':'Japanese language',
  '母':'(my) mother','名産品':'local specialty','本':'book',
  'パソコン':'personal computer','受付':'reception desk',
  '喫茶店':'café, coffee shop','国':'country, nation',
  '周辺':'surroundings, vicinity','食堂':'cafeteria, dining hall',
  '事務所':'office','建物':'building','隣':'next door, neighbor',
  '病院':'hospital','服':'clothes, clothing','木曜日':'Thursday',
  '郵便局':'post office','本屋':'bookstore',
  'エスカレーター':'escalator','コンビニ':'convenience store',
  'デジカメ':'digital camera','デパート':'department store',
  'トイレ':'restroom, toilet','眼鏡':'glasses, eyeglasses',
  '生徒':'student (school)','居間':'living room',
  'います':'to be, to exist (animate)','妹':'younger sister',
  '上':'above, on top','両親':'parents','兄弟':'siblings',
  '男':'man, male','駅':'station','教室':'classroom','猫':'cat',
  '公園':'park','子供':'child, children','外':'outside',
  '地下鉄':'subway','中':'inside, middle','庭':'garden, yard',
  '箱':'box','花屋':'flower shop','売店':'kiosk, small shop',
  '本棚':'bookshelf','ビデオ':'video, VCR','明日':'tomorrow',
  '毎朝':'every morning','今':'now','おととい':'day before yesterday',
  '火曜日':'Tuesday','学校':'school','昨日':'yesterday',
  '今朝':'this morning','研修':'training program','月曜日':'Monday',
  '今週':'this week','試験':'exam, test','仕事':'work, job',
  '出張':'business trip','先週':'last week','遅刻':'tardiness, being late',
  'いつも':'always, usually','勉強します':'to study','毎週':'every week',
  '毎日':'every day','毎晩':'every evening','来週':'next week',
  '旅行':'travel, trip','パーティー':'party','来月':'next month',
  'いっしょに':'together','弟':'younger brother',
  '交通機関':'means of transportation','先月':'last month',
  'たしか':'if I recall correctly','友達':'friend','飛行機':'airplane',
  'バス':'bus','親子丼':'oyakodon (chicken & egg rice bowl)',
  'これから':'from now on','掃除します':'to clean, to sweep',
  '卵':'egg','では':'well then, in that case','動物園':'zoo',
  '申込書':'application form','音楽':'music','サッカー':'soccer',
  'テニス':'tennis','パン':'bread','パンダ':'panda',
  'あげます':'to give','紙飛行機':'paper airplane',
  '韓国語':'Korean language','記念品':'souvenir, memento',
  '件':'matter, case','航空便':'airmail','新聞紙':'newspaper (as paper)',
  '住所':'address','花':'flower','夕方':'evening, dusk',
  '写真集':'photo album','チョコレート':'chocolate',
  'パンフレット':'pamphlet, brochure','ボールペン':'ballpoint pen',
  '料理':'cooking, dish','おいしい':'delicious, tasty',
  '温泉':'hot spring','紙':'paper','歌舞伎':'kabuki theater',
  'かわいい':'cute, adorable','薬':'medicine, drug',
  '四川料理':'Sichuan cuisine','女性':'woman, female',
  'ちょうど':'exactly, just right','天気':'weather',
  'まずい':'bad-tasting, unpleasant','水':'water','山':'mountain',
  '浴衣':'yukata (summer kimono)','スープ':'soup',
  '北京ダック':'Peking duck','海':'sea, ocean',
  '明るい':'cheerful, bright','雨':'rain',
  'いろいろ':'various, diverse','簡単':'simple, easy',
  '元気':'healthy, energetic','故郷':'hometown, homeland',
  '魚':'fish','作品':'work of art, piece','残念':'regrettable, unfortunate',
  '修学旅行':'school trip, field trip','親切':'kind, friendly',
  '自動車':'automobile, car','生活':'life, living','世界':'world',
  '彫刻':'sculpture, carving','所':'place',
  'にぎやか':'lively, bustling','人形':'doll, puppet',
  '暇':'free time, leisure','部長':'department manager',
  '平日':'weekday','物':'thing, object','紅葉':'autumn leaves',
  '有名':'famous, well-known','不便':'inconvenient',
  'どんな':'what kind of','便利':'convenient, handy',
  '脚':'leg','運転':'driving','うーん':'hmm, well...',
  '英語':'English language','会議':'meeting, conference',
  '外国':'foreign country','果物':'fruit','水泳':'swimming',
  'できます':'can, be able to',
  'ですから':'therefore, so','時々':'sometimes, occasionally',
  'どうして':'why, how come','肉':'meat',
  '下手':'unskilled, poor at','また':'again, also','窓':'window',
  '模様':'pattern, design','カラオケ':'karaoke','バラ':'rose',
  'ヒマワリ':'sunflower','ポップス':'pop music','兄':'older brother',
  '安全':'safe, safety','いちばん':'most, number one',
  '季節':'season','寿司':'sushi','席':'seat','日本酒':'Japanese sake',
  '日本料理':'Japanese cuisine','冬':'winter','春':'spring',
  'やっぱり':'after all, as expected','種類':'type, variety',
  'バナナ':'banana','ミカン':'mandarin orange','クラス':'class',
  '居酒屋':'izakaya, Japanese pub','修理':'repair',
  'かかります':'to take (time/money)','髪':'hair (of head)',
  'だいたい':'approximately, roughly','生ビール':'draft beer',
  '荷物':'luggage, baggage','ほか':'other, else','アルバム':'album',
  'ボーリング':'bowling','集める':'to collect, to gather',
  '送る':'to send, to see off','記事':'article, report',
  'こう':'like this, in this way','交差点':'intersection, crossroads',
  '食事します':'to have a meal','書類':'document, paperwork',
  '整理します':'to organize, to tidy up','太極拳':'tai chi',
  '角':'corner, turn','なかなか':'quite, considerably',
  '橋':'bridge','船便':'sea mail','右':'right side','道':'road, path',
  '電気':'electricity, light','バーベキュー':'barbecue, BBQ',
  '無理':'impossible, unreasonable','急ぐ':'to hurry, to rush',
  '落とす':'to drop, to lose','風邪':'cold (illness)',
  '気':'spirit, mind, attention','禁煙':'no smoking',
  '携帯電話':'mobile phone, cell phone','撮影禁止':'no photography',
  '市役所':'city hall','睡眠':'sleep','立入禁止':'no entry',
  '駐車禁止':'no parking','火':'fire','もしもし':'hello (on phone)',
  '薬局':'pharmacy, drugstore','ベンチ':'bench','ボート':'boat',
  '足':'foot, leg','警備':'security, guard','財布':'wallet, purse',
  '起こす':'to wake up, to cause','看板':'sign, signboard',
  '機械':'machine, machinery','建築家':'architect','子':'child',
  '航空会社':'airline company','広告':'advertisement',
  '水筒':'water bottle, canteen','設計':'design, plan',
  '操作':'operation, control','展示場':'exhibition hall',
  '天井':'ceiling','緑':'green','入場料':'admission fee',
  '鼻':'nose','目':'eye','問題':'problem, question','指':'finger',
  '横':'side, beside','練習します':'to practice',
  'クリスマスツリー':'Christmas tree','相手':'partner, other party',
  '健康':'health, healthy','恋人':'lover, sweetheart',
  '今年':'this year','混む':'to be crowded',
  '今度':'next time; this time','まず':'first of all',
  '洋服':'Western clothes, outfit','立派':'splendid, impressive',
  '恋愛':'love, romance','ノートパソコン':'laptop computer',
  '青':'blue','赤':'red','以外':'except, other than',
  '色':'color','将来':'future','うるさい':'noisy, annoying',
  '声':'voice','変える':'to change','空気':'air',
  '社会人':'working adult, member of society',
  '新春セール':'New Year sale','時間':'time','準備':'preparation',
  '音':'sound, noise','値段':'price','半額':'half price',
  '病気':'illness, disease','息子':'(my) son','もっと':'more',
  '旅行ガイド':'travel guide','デザイナー':'designer',
  'パイロット':'pilot','英会話':'English conversation',
  '遠慮':'reserve, hesitation','高級':'high class, luxury',
  '残業します':'to work overtime','品物':'goods, merchandise',
  '心配します':'to worry','上級クラス':'advanced class',
  'だいぶ':'considerably, quite','なくします':'to lose',
  '本当':'true, real','やっと':'finally, at last',
  'パスポート':'passport','レポート':'report','寮':'dormitory',
  '興味':'interest','おなか':'stomach, belly',
  '確認':'confirmation, verification','皮':'skin, peel',
  '特技':'special skill','胡弓':'erhu (Chinese fiddle)',
  'ごちそうします':'to treat (to a meal)','獅子舞':'lion dance',
  '春節':'Chinese New Year, Spring Festival','書道':'calligraphy',
  '自分':'oneself, myself','洗濯機':'washing machine',
  'みんな':'everyone, all','ギター':'guitar',
  '運動します':'to exercise','思い出す':'to remember, to recall',
  '感謝します':'to be grateful, to thank',
  '休憩時間':'break time, rest period','京劇':'Beijing opera',
  '経験':'experience','言葉':'word, language',
  '駐車場':'parking lot','報告します':'to report',
  '予約します':'to make a reservation','連休':'consecutive holidays',
  'ゴールデンウィーク':'Golden Week (Japan)',
  'あんまり':'too much, excessively','いや':'no; well',
  'うれしい':'happy, glad','おもちゃ':'toy','歌手':'singer',
  '火事':'fire (incident)','急':'sudden, urgent',
  '期間':'period, term','携帯':'mobile phone','送別会':'farewell party',
  '都合':'convenience, circumstances','転勤':'job transfer',
  '予定':'schedule, plan','連絡':'contact, communication',
  '味':'taste, flavor','気をつける':'to be careful, to watch out',
  '生地':'fabric, cloth','週末':'weekend','船':'ship, boat',
  '閉店時刻':'closing time','いっぱい':'full, a lot',
  '外出します':'to go out','研究します':'to research, to study',
  'すごい':'amazing, incredible','丁寧':'polite, careful',
  '寝坊します':'to oversleep','法律':'law',
}

# Read existing cards_data.js
with io.open(r'C:\Users\Mo_Tsai\Desktop\Google Drive\自動化測試資料夾\Japanese-tutor\cards_data.js', 'r', encoding='utf-8') as f:
    content = f.read()

def add_en(m):
    full = m.group(0)
    word_match = re.search(r"word: '([^']+)'", full)
    if not word_match:
        return full
    word = word_match.group(1)
    en = EN.get(word, '—')
    # insert meaningEn after meaning field
    return re.sub(
        r"(meaning: '[^']*')",
        r"\1, meaningEn: '" + en.replace("'", "\\'") + "'",
        full
    )

new_content = re.sub(r'\{[^}]+\}', add_en, content)

with io.open(r'C:\Users\Mo_Tsai\Desktop\Google Drive\自動化測試資料夾\Japanese-tutor\cards_data.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

# Count how many got real English vs fallback
missing = [w for w in re.findall(r"word: '([^']+)'", content) if w not in EN]
print(f'Done. Missing EN for {len(missing)} words: {missing[:10]}')
