#!/usr/bin/env python3
"""Patch cards_data.js: add example sentences for all cards with empty sentence field."""
import re, os, shutil, sys
sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = r"C:\Users\Mo_Tsai\AppData\Local\Temp\japanese-flashcard-repo"
cards_path = os.path.join(BASE_DIR, 'cards_data.js')

# word → {sentence, sentenceMeaning, sentenceMeaningEn}
SENTENCES = {
    '～円':       {'sentence': 'この りんご は 百|ひゃく 円|えん です。',
                   'sentenceMeaning': '這個蘋果是一百日圓。',
                   'sentenceMeaningEn': 'This apple costs 100 yen.'},
    '～回':       {'sentence': '一|いち 週間|しゅうかん に 三|さん 回|かい 運動|うんどう します。',
                   'sentenceMeaning': '一週運動三次。',
                   'sentenceMeaningEn': 'I exercise three times a week.'},
    '～階':       {'sentence': '私|わたし の 部屋|へや は 三|さん 階|かい です。',
                   'sentenceMeaning': '我的房間在三樓。',
                   'sentenceMeaningEn': 'My room is on the third floor.'},
    '～か月':     {'sentence': '日本語|にほんご を 六|ろく か月|かげつ 勉強|べんきょう しました。',
                   'sentenceMeaning': '學了六個月日語。',
                   'sentenceMeaningEn': 'I studied Japanese for six months.'},
    '～月':       {'sentence': '私|わたし の 誕生日|たんじょうび は 三|さん 月|がつ です。',
                   'sentenceMeaning': '我的生日在三月。',
                   'sentenceMeaningEn': 'My birthday is in March.'},
    '～個':       {'sentence': 'りんご を 三|みっ 個|こ 買い|かい ました。',
                   'sentenceMeaning': '買了三個蘋果。',
                   'sentenceMeaningEn': 'I bought three apples.'},
    '～語':       {'sentence': '彼女|かのじょ は フランス 語|ご が 話せ|はなせ ます。',
                   'sentenceMeaning': '她會說法語。',
                   'sentenceMeaningEn': 'She can speak French.'},
    '～歳':       {'sentence': '私|わたし は 二十|はたち 歳|さい です。',
                   'sentenceMeaning': '我二十歲。',
                   'sentenceMeaningEn': 'I am twenty years old.'},
    '～冊':       {'sentence': '図書館|としょかん で 本|ほん を 二|に 冊|さつ 借り|かり ました。',
                   'sentenceMeaning': '在圖書館借了兩本書。',
                   'sentenceMeaningEn': 'I borrowed two books from the library.'},
    '～時':       {'sentence': '授業|じゅぎょう は 九|く 時|じ に 始まり|はじまり ます。',
                   'sentenceMeaning': '課從九點開始。',
                   'sentenceMeaningEn': 'Class starts at nine o\'clock.'},
    '～時間':     {'sentence': '映画|えいが は 二|に 時間|じかん あります。',
                   'sentenceMeaning': '電影有兩個小時。',
                   'sentenceMeaningEn': 'The movie is two hours long.'},
    '～週間':     {'sentence': '夏休み|なつやすみ は 三|さん 週間|しゅうかん です。',
                   'sentenceMeaning': '暑假有三週。',
                   'sentenceMeaningEn': 'Summer vacation is three weeks long.'},
    '～人':       {'sentence': 'このクラス に は 二十|にじゅう 人|にん います。',
                   'sentenceMeaning': '這個班有二十個人。',
                   'sentenceMeaningEn': 'There are twenty people in this class.'},
    '～台':       {'sentence': '駐車場|ちゅうしゃじょう に 車|くるま が 五|ご 台|だい あります。',
                   'sentenceMeaning': '停車場有五輛車。',
                   'sentenceMeaningEn': 'There are five cars in the parking lot.'},
    '～中':       {'sentence': '会議|かいぎ 中|ちゅう は 電話|でんわ を しないで ください。',
                   'sentenceMeaning': '開會中請不要打電話。',
                   'sentenceMeaningEn': 'Please don\'t call during the meeting.'},
    '～度':       {'sentence': '今日|きょう の 気温|きおん は 三十|さんじゅう 度|ど です。',
                   'sentenceMeaning': '今天氣溫三十度。',
                   'sentenceMeaningEn': 'Today\'s temperature is 30 degrees.'},
    '～日':       {'sentence': '今月|こんげつ の 十五|じゅうご 日|にち に 試験|しけん が あります。',
                   'sentenceMeaning': '這個月十五號有考試。',
                   'sentenceMeaningEn': 'There is an exam on the 15th of this month.'},
    '～年':       {'sentence': '日本語|にほんご を 三|さん 年|ねん 勉強|べんきょう して います。',
                   'sentenceMeaning': '已經學了三年日語。',
                   'sentenceMeaningEn': 'I have been studying Japanese for three years.'},
    '～杯':       {'sentence': 'コーヒー を 一|いっ 杯|ぱい ください。',
                   'sentenceMeaning': '請給我一杯咖啡。',
                   'sentenceMeaningEn': 'Please give me one cup of coffee.'},
    '～番':       {'sentence': '私|わたし は 三|さん 番|ばん です。',
                   'sentenceMeaning': '我是三號。',
                   'sentenceMeaningEn': 'I am number three.'},
    '～匹':       {'sentence': '猫|ねこ が 三|さん 匹|びき います。',
                   'sentenceMeaning': '有三隻貓。',
                   'sentenceMeaningEn': 'There are three cats.'},
    '～分':       {'sentence': '駅|えき まで 十|じゅっ 分|ぷん かかります。',
                   'sentenceMeaning': '到車站要十分鐘。',
                   'sentenceMeaningEn': 'It takes ten minutes to the station.'},
    '～本':       {'sentence': '鉛筆|えんぴつ が 三|さん 本|ぼん あります。',
                   'sentenceMeaning': '有三支鉛筆。',
                   'sentenceMeaningEn': 'There are three pencils.'},
    '～枚':       {'sentence': '切手|きって を 五|ご 枚|まい 買い|かい ました。',
                   'sentenceMeaning': '買了五張郵票。',
                   'sentenceMeaningEn': 'I bought five stamps.'},
    '～前':       {'sentence': '三|さん 年|ねん 前|まえ に 日本|にほん に 来|き ました。',
                   'sentenceMeaning': '三年前來到了日本。',
                   'sentenceMeaningEn': 'I came to Japan three years ago.'},
    '～屋':       {'sentence': 'あの 本|ほん 屋|や は 大きい|おおきい です。',
                   'sentenceMeaning': '那家書店很大。',
                   'sentenceMeaningEn': 'That bookstore is large.'},
    'いい':       {'sentence': '今日|きょう は いい 天気|てんき ですね。',
                   'sentenceMeaning': '今天天氣真好呢。',
                   'sentenceMeaningEn': 'The weather is nice today, isn\'t it?'},
    'キロ':       {'sentence': '体重|たいじゅう が 五|ご キロ 増え|ふえ ました。',
                   'sentenceMeaning': '體重增加了五公斤。',
                   'sentenceMeaningEn': 'My weight increased by five kilograms.'},
    '～くらい':   {'sentence': '十|じゅっ 分|ぷん くらい 待ち|まち ました。',
                   'sentenceMeaning': '等了大約十分鐘。',
                   'sentenceMeaningEn': 'I waited for about ten minutes.'},
    'そう':       {'sentence': '「明日|あした 来ます|き ます か。」「そう です。」',
                   'sentenceMeaning': '「明天會來嗎？」「是的。」',
                   'sentenceMeaningEn': '"Will you come tomorrow?" "Yes, I will."'},
    'そうして':   {'sentence': '宿題|しゅくだい を して 、そうして 寝|ね ました。',
                   'sentenceMeaning': '做了功課，然後睡覺了。',
                   'sentenceMeaningEn': 'I did my homework and then went to sleep.'},
    'あ':         {'sentence': 'あ、財布|さいふ を 忘れ|わすれ ました！',
                   'sentenceMeaning': '啊，我忘了帶錢包！',
                   'sentenceMeaningEn': 'Oh, I forgot my wallet!'},
    'アフリカ':   {'sentence': 'アフリカ は 広い|ひろい 大陸|たいりく です。',
                   'sentenceMeaning': '非洲是廣闊的大陸。',
                   'sentenceMeaningEn': 'Africa is a vast continent.'},
    '上がる':     {'sentence': '値段|ねだん が 上がり|あがり ました。',
                   'sentenceMeaning': '價格上漲了。',
                   'sentenceMeaningEn': 'The price went up.'},
    '挨拶':       {'sentence': '毎朝|まいあさ 挨拶|あいさつ を します。',
                   'sentenceMeaning': '每天早上打招呼。',
                   'sentenceMeaningEn': 'I greet people every morning.'},
    'アジア':     {'sentence': '日本|にほん は アジア に あります。',
                   'sentenceMeaning': '日本位於亞洲。',
                   'sentenceMeaningEn': 'Japan is in Asia.'},
    '赤ちゃん':   {'sentence': '隣|となり の 赤ちゃん は かわいい です。',
                   'sentenceMeaning': '鄰居的嬰兒很可愛。',
                   'sentenceMeaningEn': 'The neighbor\'s baby is cute.'},
    '赤ん坊':     {'sentence': '赤ん坊 は よく 泣き|なき ます。',
                   'sentenceMeaning': '嬰兒常常哭。',
                   'sentenceMeaningEn': 'Babies cry a lot.'},
    'アクセサリー': {'sentence': '彼女|かのじょ は アクセサリー が 好き|す です。',
                   'sentenceMeaning': '她喜歡飾品。',
                   'sentenceMeaningEn': 'She likes accessories.'},
    'アメリカ':   {'sentence': '友達|ともだち は アメリカ から 来|き ました。',
                   'sentenceMeaning': '朋友從美國來的。',
                   'sentenceMeaningEn': 'My friend came from America.'},
    'アナウンサー': {'sentence': '彼|かれ は テレビ の アナウンサー です。',
                   'sentenceMeaning': '他是電視播音員。',
                   'sentenceMeaningEn': 'He is a TV announcer.'},
    'あんな':     {'sentence': 'あんな 大きい|おおきい 犬|いぬ は 初めて|はじめて 見|み ました。',
                   'sentenceMeaning': '第一次看到那麼大的狗。',
                   'sentenceMeaningEn': 'I saw such a big dog for the first time.'},
    '案内':       {'sentence': '係員|かかりいん が 案内|あんない して くれました。',
                   'sentenceMeaning': '工作人員幫我帶路了。',
                   'sentenceMeaningEn': 'The staff member guided me.'},
    '安心':       {'sentence': '試験|しけん が 終わっ|おわっ て 安心|あんしん しました。',
                   'sentenceMeaning': '考試結束後放心了。',
                   'sentenceMeaningEn': 'I felt relieved when the exam was over.'},
    'アルバイト': {'sentence': '週末|しゅうまつ に アルバイト を して います。',
                   'sentenceMeaning': '週末在打工。',
                   'sentenceMeaningEn': 'I work part-time on weekends.'},
    'アルコール': {'sentence': '医者|いしゃ に アルコール を やめる よう 言わ|いわ れました。',
                   'sentenceMeaning': '被醫生說要戒酒。',
                   'sentenceMeaningEn': 'The doctor told me to stop drinking alcohol.'},
    '浅い':       {'sentence': 'この 川|かわ は 浅い|あさい から 安全|あんぜん です。',
                   'sentenceMeaning': '這條河水淺，很安全。',
                   'sentenceMeaningEn': 'This river is shallow, so it\'s safe.'},
    '遊び':       {'sentence': '子供|こども たち は 遊び|あそび が 大好き|だいすき です。',
                   'sentenceMeaning': '孩子們非常喜歡玩耍。',
                   'sentenceMeaningEn': 'Children love playing.'},
    '集まる':     {'sentence': '公園|こうえん に 人|ひと が たくさん 集まり|あつまり ました。',
                   'sentenceMeaning': '公園裡聚集了很多人。',
                   'sentenceMeaningEn': 'Many people gathered in the park.'},
    '謝る':       {'sentence': '失礼|しつれい な ことを して 謝り|あやまり ました。',
                   'sentenceMeaning': '因為失禮的事而道歉了。',
                   'sentenceMeaningEn': 'I apologized for being rude.'},
    '倍':         {'sentence': '去年|きょねん より 倍|ばい 売れ|うれ ました。',
                   'sentenceMeaning': '比去年賣出了兩倍。',
                   'sentenceMeaningEn': 'It sold twice as much as last year.'},
    '番組':       {'sentence': '好き|す な テレビ 番組|ばんぐみ を 毎日|まいにち 見|み ます。',
                   'sentenceMeaning': '每天看喜歡的電視節目。',
                   'sentenceMeaningEn': 'I watch my favorite TV program every day.'},
    '場所':       {'sentence': '待ち合わせ|まちあわせ の 場所|ばしょ を 決め|き め ましょう。',
                   'sentenceMeaning': '決定集合地點吧。',
                   'sentenceMeaningEn': 'Let\'s decide on a meeting place.'},
    'ベル':       {'sentence': 'ベル が 鳴っ|なっ たら 授業|じゅぎょう を 始め|はじめ ます。',
                   'sentenceMeaning': '鈴響了就開始上課。',
                   'sentenceMeaningEn': 'We start class when the bell rings.'},
    '美術館':     {'sentence': '日曜日|にちようび に 美術館|びじゅつかん へ 行き|いき ました。',
                   'sentenceMeaning': '星期日去了美術館。',
                   'sentenceMeaningEn': 'I went to the art museum on Sunday.'},
    'びっくり':   {'sentence': '急|きゅう に 大きい|おおきい 声|こえ が して びっくり しました。',
                   'sentenceMeaning': '突然發出很大的聲音，嚇了一跳。',
                   'sentenceMeaningEn': 'I was startled by a sudden loud noise.'},
    'ビル':       {'sentence': 'あの ビル は 三十|さんじゅう 階建て|かいだて です。',
                   'sentenceMeaning': '那棟大樓有三十層。',
                   'sentenceMeaningEn': 'That building has thirty floors.'},
    '僕':         {'sentence': '僕|ぼく は 高校生|こうこうせい です。',
                   'sentenceMeaning': '我是高中生。',
                   'sentenceMeaningEn': 'I am a high school student.'},
    '貿易':       {'sentence': '日本|にほん は 外国|がいこく と 貿易|ぼうえき を して います。',
                   'sentenceMeaning': '日本與外國進行貿易往來。',
                   'sentenceMeaningEn': 'Japan trades with foreign countries.'},
    'ぶどう':     {'sentence': '秋|あき に なる と ぶどう が おいしく なります。',
                   'sentenceMeaning': '秋天一到葡萄就變得好吃了。',
                   'sentenceMeaningEn': 'Grapes become delicious in autumn.'},
    '文学':       {'sentence': '彼女|かのじょ は 日本|にほん 文学|ぶんがく を 専攻|せんこう して います。',
                   'sentenceMeaning': '她主修日本文學。',
                   'sentenceMeaningEn': 'She majors in Japanese literature.'},
    '文化':       {'sentence': '日本|にほん の 文化|ぶんか に 興味|きょうみ が あります。',
                   'sentenceMeaning': '我對日本文化有興趣。',
                   'sentenceMeaningEn': 'I am interested in Japanese culture.'},
    '文法':       {'sentence': '文法|ぶんぽう を しっかり 覚え|おぼえ ましょう。',
                   'sentenceMeaning': '要好好記住文法。',
                   'sentenceMeaningEn': 'Let\'s learn grammar properly.'},
    'ちゃん':     {'sentence': '田中|たなか ちゃん は 元気|げんき ですか。',
                   'sentenceMeaning': '田中小妹妹你好嗎？',
                   'sentenceMeaningEn': 'How are you, Tanaka-chan?'},
    'チェック':   {'sentence': '予約|よやく を チェック して ください。',
                   'sentenceMeaning': '請確認預約。',
                   'sentenceMeaningEn': 'Please check the reservation.'},
    '血':         {'sentence': '転ん|ころん で 膝|ひざ から 血|ち が 出|で ました。',
                   'sentenceMeaning': '跌倒後膝蓋流血了。',
                   'sentenceMeaningEn': 'I fell and my knee bled.'},
    '力':         {'sentence': 'スポーツ で 力|ちから を つけます。',
                   'sentenceMeaning': '透過運動增強體力。',
                   'sentenceMeaningEn': 'I build strength through sports.'},
    '地理':       {'sentence': '高校|こうこう で 地理|ちり を 勉強|べんきょう しました。',
                   'sentenceMeaning': '高中學過地理。',
                   'sentenceMeaningEn': 'I studied geography in high school.'},
    '中学校':     {'sentence': '弟|おとうと は 今年|ことし 中学校|ちゅうがっこう に 入り|はいり ました。',
                   'sentenceMeaning': '弟弟今年進了中學。',
                   'sentenceMeaningEn': 'My younger brother entered middle school this year.'},
    '注意':       {'sentence': '道|みち を 渡る|わたる 時|とき は 注意|ちゅうい して ください。',
                   'sentenceMeaning': '過馬路時請注意。',
                   'sentenceMeaningEn': 'Please be careful when crossing the road.'},
    '注射':       {'sentence': 'インフルエンザ の 注射|ちゅうしゃ を 受け|うけ ました。',
                   'sentenceMeaning': '打了流感疫苗。',
                   'sentenceMeaningEn': 'I got a flu shot.'},
    '大学生':     {'sentence': '姉|あね は 大学生|だいがくせい です。',
                   'sentenceMeaning': '姐姐是大學生。',
                   'sentenceMeaningEn': 'My older sister is a university student.'},
    '大事':       {'sentence': '健康|けんこう が 一番|いちばん 大事|だいじ です。',
                   'sentenceMeaning': '健康最重要。',
                   'sentenceMeaningEn': 'Health is the most important thing.'},
    '暖房':       {'sentence': '冬|ふゆ は 暖房|だんぼう を 入れ|いれ ます。',
                   'sentenceMeaning': '冬天開暖氣。',
                   'sentenceMeaningEn': 'We turn on the heater in winter.'},
    '男性':       {'sentence': 'その 男性|だんせい は 親切|しんせつ に 教え|おしえ て くれました。',
                   'sentenceMeaning': '那位男性親切地告訴了我。',
                   'sentenceMeaningEn': 'That man kindly told me.'},
    'できるだけ': {'sentence': 'できるだけ 早く|はやく 来|き て ください。',
                   'sentenceMeaning': '請盡可能早點來。',
                   'sentenceMeaningEn': 'Please come as early as possible.'},
    '電報':       {'sentence': '結婚|けっこん の お祝い|いわい に 電報|でんぽう を 送り|おくり ました。',
                   'sentenceMeaning': '為了慶賀結婚發了電報。',
                   'sentenceMeaningEn': 'I sent a telegram to congratulate the wedding.'},
    '電灯':       {'sentence': '部屋|へや の 電灯|でんとう が 切れ|きれ ました。',
                   'sentenceMeaning': '房間的燈泡壞了。',
                   'sentenceMeaningEn': 'The light in the room burned out.'},
    'どんどん':   {'sentence': '日本語|にほんご が どんどん 上手|じょうず に なって います。',
                   'sentenceMeaning': '日語越來越好了。',
                   'sentenceMeaningEn': 'My Japanese is getting better and better.'},
    '泥棒':       {'sentence': '昨夜|さくや 泥棒|どろぼう が 入り|はいり ました。',
                   'sentenceMeaning': '昨晚有小偷闖入。',
                   'sentenceMeaningEn': 'A thief broke in last night.'},
    '道具':       {'sentence': '料理|りょうり の 道具|どうぐ を 買い|かい ました。',
                   'sentenceMeaning': '買了烹飪工具。',
                   'sentenceMeaningEn': 'I bought cooking tools.'},
    '枝':         {'sentence': '木|き の 枝|えだ が 風|かぜ で 折れ|おれ ました。',
                   'sentenceMeaning': '樹枝被風折斷了。',
                   'sentenceMeaningEn': 'The tree branch broke in the wind.'},
    '選ぶ':       {'sentence': '好き|す な 色|いろ を 選ん|えらん で ください。',
                   'sentenceMeaning': '請選擇喜歡的顏色。',
                   'sentenceMeaningEn': 'Please choose your favorite color.'},
    'ファックス': {'sentence': '書類|しょるい を ファックス で 送り|おくり ました。',
                   'sentenceMeaning': '用傳真機發送了文件。',
                   'sentenceMeaningEn': 'I sent the documents by fax.'},
    '増える':     {'sentence': '最近|さいきん 外国人|がいこくじん 観光客|かんこうきゃく が 増え|ふえ ました。',
                   'sentenceMeaning': '最近外國觀光客增加了。',
                   'sentenceMeaningEn': 'The number of foreign tourists has increased recently.'},
    '深い':       {'sentence': 'この 湖|みずうみ は 深い|ふかい です。',
                   'sentenceMeaning': '這個湖很深。',
                   'sentenceMeaningEn': 'This lake is deep.'},
    '復習':       {'sentence': '毎日|まいにち 授業|じゅぎょう の 復習|ふくしゅう を します。',
                   'sentenceMeaning': '每天複習課程內容。',
                   'sentenceMeaningEn': 'I review my lessons every day.'},
    '複雑':       {'sentence': 'この 問題|もんだい は 複雑|ふくざつ で 難しい|むずかしい です。',
                   'sentenceMeaning': '這個問題複雜又困難。',
                   'sentenceMeaningEn': 'This problem is complicated and difficult.'},
    '踏む':       {'sentence': '電車|でんしゃ の 中|なか で 足|あし を 踏ま|ふま れました。',
                   'sentenceMeaning': '在電車裡被踩到腳了。',
                   'sentenceMeaningEn': 'My foot was stepped on in the train.'},
    '降り出す':   {'sentence': '急|きゅう に 雨|あめ が 降り出し|ふりだし ました。',
                   'sentenceMeaning': '突然開始下雨了。',
                   'sentenceMeaningEn': 'It suddenly started raining.'},
    '布団':       {'sentence': '寒い|さむい から 布団|ふとん を 二枚|ふたまい 使い|つかい ます。',
                   'sentenceMeaning': '因為冷所以用了兩條被子。',
                   'sentenceMeaningEn': 'I use two futons because it is cold.'},
    '太る':       {'sentence': '食べ|た すぎて 太り|ふとり ました。',
                   'sentenceMeaning': '因為吃太多而胖了。',
                   'sentenceMeaningEn': 'I gained weight from eating too much.'},
    '普通':       {'sentence': '普通|ふつう の 生活|せいかつ が 一番|いちばん 幸せ|しあわせ だと 思い|おもい ます。',
                   'sentenceMeaning': '我覺得普通的生活是最幸福的。',
                   'sentenceMeaningEn': 'I think an ordinary life is the happiest.'},
    'ガラス':     {'sentence': 'ガラス の コップ が 割れ|われ ました。',
                   'sentenceMeaning': '玻璃杯破了。',
                   'sentenceMeaningEn': 'The glass cup broke.'},
    'ガソリン':   {'sentence': '車|くるま の ガソリン が なくなり ました。',
                   'sentenceMeaning': '車子沒油了。',
                   'sentenceMeaningEn': 'The car ran out of gasoline.'},
    'ガソリンスタンド': {'sentence': 'ガソリンスタンド で 油|あぶら を 入れ|いれ ました。',
                   'sentenceMeaning': '在加油站加了油。',
                   'sentenceMeaningEn': 'I filled up at the gas station.'},
    'ガス':       {'sentence': 'ガス を 使っ|つかっ て 料理|りょうり します。',
                   'sentenceMeaning': '用瓦斯烹飪。',
                   'sentenceMeaningEn': 'I cook using gas.'},
    '原因':       {'sentence': '病気|びょうき の 原因|げんいん を 調べ|しらべ ます。',
                   'sentenceMeaning': '調查生病的原因。',
                   'sentenceMeaningEn': 'I will investigate the cause of the illness.'},
    '下宿':       {'sentence': '大学|だいがく の 近く|ちかく に 下宿|げしゅく して います。',
                   'sentenceMeaning': '在大學附近租房子住。',
                   'sentenceMeaningEn': 'I am boarding near the university.'},
    '技術':       {'sentence': 'この 会社|かいしゃ の 技術|ぎじゅつ は 高い|たかい です。',
                   'sentenceMeaning': '這家公司的技術很高超。',
                   'sentenceMeaningEn': 'This company\'s technology is advanced.'},
    'ごちそう':   {'sentence': 'お客さん|きゃくさん に ごちそう を 作り|つくり ました。',
                   'sentenceMeaning': '為客人做了豐盛的料理。',
                   'sentenceMeaningEn': 'I prepared a feast for the guests.'},
    'ごみ':       {'sentence': '毎朝|まいあさ ごみ を 出し|だし ます。',
                   'sentenceMeaning': '每天早上倒垃圾。',
                   'sentenceMeaningEn': 'I take out the trash every morning.'},
    'ご覧になる': {'sentence': 'この 写真|しゃしん を ご覧|ごらん に なって ください。',
                   'sentenceMeaning': '請看一下這張照片。',
                   'sentenceMeaningEn': 'Please take a look at this photo.'},
    'ご主人':     {'sentence': 'ご主人|ごしゅじん は お 仕事|しごと は 何|なん ですか。',
                   'sentenceMeaning': '您先生的工作是什麼？',
                   'sentenceMeaningEn': 'What does your husband do for work?'},
    'ご存じ':     {'sentence': '田中|たなか さん を ご存じ|ごぞんじ ですか。',
                   'sentenceMeaning': '您認識田中先生嗎？',
                   'sentenceMeaningEn': 'Do you know Mr. Tanaka?'},
    '具合':       {'sentence': '具合|ぐあい は いかが ですか。',
                   'sentenceMeaning': '您身體狀況如何？',
                   'sentenceMeaningEn': 'How are you feeling?'},
    '拝見':       {'sentence': '資料|しりょう を 拝見|はいけん します。',
                   'sentenceMeaning': '我來看一下資料。',
                   'sentenceMeaningEn': 'I will take a look at the documents.'},
    '歯医者':     {'sentence': '歯|は が 痛く|いたく て 歯医者|はいしゃ へ 行き|いき ました。',
                   'sentenceMeaning': '牙齒痛所以去看了牙醫。',
                   'sentenceMeaningEn': 'My tooth hurt so I went to the dentist.'},
    'はっきり':   {'sentence': 'もっと はっきり 話し|はなし て ください。',
                   'sentenceMeaning': '請說得更清楚一點。',
                   'sentenceMeaningEn': 'Please speak more clearly.'},
    '運ぶ':       {'sentence': '重い|おもい 荷物|にもつ を 運ん|はこん で もらいました。',
                   'sentenceMeaning': '請人幫我搬了重行李。',
                   'sentenceMeaningEn': 'I had someone carry my heavy luggage.'},
    '花見':       {'sentence': '春|はる に みんな で 花見|はなみ を しました。',
                   'sentenceMeaning': '春天大家一起賞了櫻花。',
                   'sentenceMeaningEn': 'We all went cherry blossom viewing in spring.'},
    'ハンドバッグ': {'sentence': '母|はは は 新しい|あたらしい ハンドバッグ を 買い|かい ました。',
                   'sentenceMeaning': '媽媽買了一個新手提包。',
                   'sentenceMeaningEn': 'My mother bought a new handbag.'},
    '反対':       {'sentence': '父|ちち は 私|わたし の 留学|りゅうがく に 反対|はんたい して います。',
                   'sentenceMeaning': '父親反對我留學。',
                   'sentenceMeaningEn': 'My father opposes my studying abroad.'},
    '払う':       {'sentence': 'レジ で お 金|かね を 払い|はらい ます。',
                   'sentenceMeaning': '在收銀台付款。',
                   'sentenceMeaningEn': 'I pay at the register.'},
    '発音':       {'sentence': '日本語|にほんご の 発音|はつおん は 難しく|むずかしく ない です。',
                   'sentenceMeaning': '日語的發音不難。',
                   'sentenceMeaningEn': 'Japanese pronunciation is not difficult.'},
    '林':         {'sentence': '学校|がっこう の 近く|ちかく に 林|はやし が あります。',
                   'sentenceMeaning': '學校附近有樹林。',
                   'sentenceMeaningEn': 'There is a grove near the school.'},
    '恥ずかしい': {'sentence': '皆|みんな の 前|まえ で 間違え|まちがえ て 恥ずかしかっ|はずかしかっ た です。',
                   'sentenceMeaning': '在大家面前答錯了，很丟臉。',
                   'sentenceMeaningEn': 'I was embarrassed when I made a mistake in front of everyone.'},
    # Extra cards found (葉, 大体 etc from JLPT N4)
    '葉':         {'sentence': '秋|あき に なる と 木|き の 葉|は が 赤く|あかく なります。',
                   'sentenceMeaning': '秋天一到，樹葉就變紅了。',
                   'sentenceMeaningEn': 'The leaves turn red in autumn.'},
    '大体':       {'sentence': '宿題|しゅくだい は 大体|だいたい 終わり|おわり ました。',
                   'sentenceMeaning': '功課大致做完了。',
                   'sentenceMeaningEn': 'I have mostly finished my homework.'},
    # counter variants
    '～人（にん）': {'sentence': 'この 部屋|へや に 五|ご 人|にん 入れ|はいれ ます。',
                   'sentenceMeaning': '這個房間可以容納五個人。',
                   'sentenceMeaningEn': 'Five people can fit in this room.'},
}

def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")

# ── Load and patch ────────────────────────────────────────────────────────────
with open(cards_path, encoding='utf-8') as f:
    js = f.read()

patched = 0
not_found = []

for word, data in SENTENCES.items():
    # Find the card block with this word and empty sentence
    pattern = (
        r"(word: '" + re.escape(word) + r"'(?:[^}](?!sentence: '[^']+')){0,300}"
        r"sentence: '')([^}]*sentenceMeaning: '')([^}]*sentenceMeaningEn: '')"
    )
    # Simpler: find sentence: '' in a block that has word: 'X'
    # We'll do a two-pass approach: find the block, then replace fields

    # Find blocks containing this word with empty sentence
    block_pat = re.compile(
        r'(\{\s*level:[^}]*?word: \'' + re.escape(word) + r'\'[^}]*?sentence: \'\')[^}]*\}',
        re.DOTALL
    )
    m = block_pat.search(js)
    if not m:
        not_found.append(word)
        continue

    start, end = m.start(), m.end()
    block = js[start:end]

    # Only patch if sentence is actually empty
    if "sentence: ''" not in block:
        continue

    new_block = block
    new_block = re.sub(r"sentence: ''", f"sentence: '{esc(data['sentence'])}'", new_block, count=1)
    new_block = re.sub(r"sentenceMeaning: ''", f"sentenceMeaning: '{esc(data['sentenceMeaning'])}'", new_block, count=1)
    new_block = re.sub(r"sentenceMeaningEn: ''", f"sentenceMeaningEn: '{esc(data['sentenceMeaningEn'])}'", new_block, count=1)

    js = js[:start] + new_block + js[end:]
    patched += 1
    print(f"  ✓ {word}")

print(f"\nPatched: {patched}")
if not_found:
    print(f"Not found in cards (may already have sentence or word mismatch):")
    for w in not_found:
        print(f"  - {w}")

with open(cards_path, 'w', encoding='utf-8') as f:
    f.write(js)

shutil.copy2(cards_path, os.path.join(REPO_DIR, 'cards_data.js'))

remaining = js.count("sentence: ''")
print(f"\nRemaining cards without sentence: {remaining}")
print("Done. Copied to repo.")
